---
#list of packages required for Oracle
packages:
  - binutils
  - compat-libcap1
  - gcc
  - gcc-c++
  - glibc.i686 
  - glibc
  - glibc-devel.i686 
  - glibc-devel
  - ksh
  - libaio.i686 
  - libaio
  - libaio-devel.i686 
  - libaio-devel.x86_64
  - libgcc.i686 
  - libgcc
  - libstdc++.i686 
  - libstdc++
  - libstdc++-devel.i686 
  - libstdc++-devel
  - libXi.i686 
  - libXi
  - libXtst.i686 
  - libXtst
  - make
  - sysstat
  - unzip
  - xorg-x11-xauth
  - xorg-x11-utils
  - xterm
...