# variables needed to be provided in extra_vars:
# target
# dbo_username
# db_name
# db_service_name
---
- name: SierraPostInstall
  hosts: '{{ target }}'
  gather_facts: no 
  tasks:
    - shell: source /APPL/{{ dbo_username }}/users/{{ dbo_username }}/.fnxrc && /APPL/{{ dbo_username }}/bin/reglogin -c -U {{ dbo_username }} -P fnxltd11 -D {{ db_name }} -S {{ db_service_name }}
      args:
        executable: "/bin/tcsh"
        chdir: /APPL/{{ dbo_username }}/server
        creates: /APPL/{{ dbo_username }}/server/reglogin.info
    - name: Creating softlinks
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      with_items:
        - { src: '/APPL/{{ dbo_username }}/server/reglogin.info', dest: '/APPL/{{ dbo_username }}/server/reglogin.info.{{ dbo_username }}' }
        - { src: '/APPL/{{ dbo_username }}/server/reglogin.info', dest: '/APPL/{{ dbo_username }}/server/reglogin.fx.info' }
    - name: Create parameter file for CreateDboAndFixUsers.sh
      shell: |
         source /APPL/{{ dbo_username }}/users/{{ dbo_username }}/.fnxrc
         echo h0bb1t > ~/parameter.txt
         echo 0 >> ~/parameter.txt
         echo y >> ~/parameter.txt
      args:
        executable: "/bin/tcsh"
        creates: ~/parameter.txt
    - name: Run CreateDboAndFixUsers.sh
      shell: source /APPL/{{ dbo_username }}/users/{{ dbo_username }}/.fnxrc && cat ~/parameter.txt | /APPL/{{ dbo_username }}/script/CreateDboSsoAndFixUsers.sh -T O -S {{ db_service_name }} -U {{ dbo_username }} -P fnxltd11 -u {{ dbo_username }}SSO -p fnxltd11
      args:
        executable: "/bin/tcsh"
    - name: Update sydefault and sbdefault tables for visibility
      shell: |
        source /APPL/{{ dbo_username }}/users/{{ dbo_username }}/.fnxrc
        echo alter table fnxuser disable all triggers\; | sqlplus {{ dbo_username }}/fnxltd11@{{ db_service_name }}
        echo alter table sydefault disable all triggers\; | sqlplus {{ dbo_username }}/fnxltd11@{{ db_service_name }}
        echo update sydefault set visibility='NORMAL' where visibility is NULL\; | sqlplus {{ dbo_username }}/fnxltd11@{{ db_service_name }}
        echo alter table sydefault enable all triggers\; | sqlplus {{ dbo_username }}/fnxltd11@{{ db_service_name }}
        echo alter table sbdefault disable all triggers\; | sqlplus {{ dbo_username }}/fnxltd11@{{ db_service_name }}
        echo update sbdefault set visibility='NORMAL' where visibility is NULL\; | sqlplus {{ dbo_username }}/fnxltd11@{{ db_service_name }}
        echo alter table sbdefault enable all triggers\; | sqlplus {{ dbo_username }}/fnxltd11@{{ db_service_name }}
      args:
        executable: "/bin/tcsh"
      # Permissions setup for Sierra dirs
    - name: Permissions setup for Sierra dirs
      command:   chmod -R o-rwx /APPL/{{ dbo_username }}
    - command:   chmod -R g-w  /APPL/{{ dbo_username }}
    - command:   chmod g+rw /APPL/{{ dbo_username }}/log
    - command:   chmod g+rw /APPL/{{ dbo_username }}/rep
    - command:   chmod g+rw /APPL/{{ dbo_username }}/export
    - command:   chmod g+rw /APPL/{{ dbo_username }}/script
    - command:   chmod g+rw /APPL/{{ dbo_username }}/bin
    - name: Copy aspen.cfg
      copy:
        remote_src: yes
        src: /APPL/{{ dbo_username }}/server/aspen_template.cfg
        dest: /APPL/{{ dbo_username }}/server/aspen.cfg
    - name: Copy sierra.license
      copy:
        remote_src: no
        src: /etc/ansible/playbooks/files/sierra.license.development
        dest: /APPL/{{ dbo_username }}/sierra.license
    - name: Copy check_patch_log script
      copy:
        remote_src: no
        src: /etc/ansible/playbooks/files/check_patch_log_file
        dest: /APPL/{{ dbo_username }}/users/{{ dbo_username }}/check_patch_log_file
  become: true
  become_user: "{{ dbo_username }}"
...