apiVersion: apps/v1
kind: Deployment
metadata:
  name: realworld
spec:
  replicas: 3
  selector:
    matchLabels:
      name: conduit_blog_app
      app: web
  template:
    metadata:
      labels:
        name: conduit_blog_app
        app: web
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: rw-container
        image: losmino13/realworld:v1.2.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        imagePullPolicy: Always
        ports:
          - containerPort: 8000
