apiVersion: v1
kind: Pod
metadata:
  name: realworld
  labels:
    name: conduit_blog_app
    app: web
spec:
  containers:
  - name: rw-container
    image: losmino13/realworld:v1.2.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8000
